baseURL: https://latihan-hugo-bootstrap.netlify.app/
languageCode: en-us
theme: juwayritema
title: Latihan Hugo Bootstrap

module:
  hugoVersion:
    min: 0.92.0

module:
  imports:
    - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5